{
 "title": "GOST",
 "description": "GOST v3 Metrics Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "description": "Up Time",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"gost\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gost\"}"
    }
   ]
  },
  {
   "title": "VM",
   "type": "stat",
   "description": "Virtual memory",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"gost\"}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "description": "Number of GOST Services",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gost_services" }
   ]
  },
  {
   "title": "Inputs",
   "type": "stat",
   "description": "Total input data",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gost_service_transfer_input_bytes_total)"
    }
   ]
  },
  {
   "title": "Outputs",
   "type": "stat",
   "description": "Total output data",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gost_service_transfer_output_bytes_total)"
    }
   ]
  },
  {
   "title": "RIF",
   "type": "stat",
   "description": "Requests in flight",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gost_service_requests_in_flight)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of service handler errors",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gost_service_handler_errors_total)"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Resident memory",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gost\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"gost\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines/Threads",
   "type": "timeseries",
   "description": "Number of goroutines and threads that currently exist",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"gost\"}",
     "legendFormat": "goroutines ({{instance}})"
    },
    {
     "expr": "go_threads{job=\"gost\"}",
     "legendFormat": "threads ({{instance}})"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "description": "Current Number of Open File Descriptors",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "process_max_fds{job=\"gost\"}",
     "legendFormat": "max ({{instance}})"
    },
    {
     "expr": "process_open_fds{job=\"gost\"}",
     "legendFormat": "open ({{instance}})"
    }
   ]
  },
  { "title": "GOST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per Second",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(gost_service_requests_total[1m])",
     "legendFormat": "{{service}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Requests in Flight",
   "type": "timeseries",
   "description": "Number of Requests in Flight",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gost_service_requests_in_flight",
     "legendFormat": "{{service}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Handler Errors",
   "type": "timeseries",
   "description": "Service handler errors per second",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gost_service_handler_errors_total[1m])",
     "legendFormat": "{{service}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Chain Errors",
   "type": "timeseries",
   "description": "Chain errors per second",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gost_chain_errors_total[1m])",
     "legendFormat": "{{chain}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Input",
   "type": "timeseries",
   "description": "Data Input per Second",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(gost_service_transfer_input_bytes_total[1m])",
     "legendFormat": "{{service}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Output",
   "type": "timeseries",
   "description": "Data Output per Second",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(gost_service_transfer_output_bytes_total[1m])",
     "legendFormat": "{{service}} ({{instance}})"
    }
   ]
  }
 ]
}